# Generated by Django 3.2.11 on 2024-09-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='carousel_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
