# Generated by Django 5.0 on 2024-04-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
