# Generated by Django 5.0 on 2024-04-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0002_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='url',
            new_name='carousel_url',
        ),
    ]
