# Generated by Django 5.0.1 on 2024-01-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbooklist',
            old_name='user_name',
            new_name='author',
        ),
        migrations.AddField(
            model_name='textbooklist',
            name='exhibitor',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
