# Generated by Django 5.0.1 on 2024-01-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_market', '0002_rename_user_name_textbooklist_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='textbookList',
            new_name='BookMarketList',
        ),
    ]
