# Generated by Django 5.0.1 on 2024-01-27 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_market', '0003_rename_textbooklist_bookmarketlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarketlist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
