# Generated by Django 5.0.1 on 2024-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_market', '0004_alter_bookmarketlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarketlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
