# Generated by Django 5.0.1 on 2024-01-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_market', '0005_alter_bookmarketlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarketlist',
            name='all_grade',
            field=models.BooleanField(default=0, help_text='一般教養ならTrue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmarketlist',
            name='depertment',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmarketlist',
            name='grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
