# Generated by Django 5.0.1 on 2024-01-27 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_market', '0006_bookmarketlist_all_grade_bookmarketlist_depertment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarketlist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
