# Generated by Django 3.2.11 on 2024-01-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_market', '0007_alter_bookmarketlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarketlist',
            name='image',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
