# Generated by Django 3.2.11 on 2024-01-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_market', '0012_alter_bookmarketlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarketlist',
            name='image',
            field=models.ImageField(upload_to='book_image'),
        ),
    ]
