# Generated by Django 3.2.11 on 2024-01-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_market', '0013_alter_bookmarketlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarketlist',
            name='image',
            field=models.ImageField(null=True, upload_to='book_image'),
        ),
    ]
