# Generated by Django 5.0 on 2024-02-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('sunny', '晴れ'), ('cloudy', 'くもり'), ('rainy', '雨'), ('other', 'その他')], max_length=10)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
