# Generated by Django 5.0 on 2024-02-15 23:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_voterecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='last_reset_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
