# Generated by Django 5.0 on 2024-02-20 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_vote_last_reset_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='last_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
