# Generated by Django 3.2.11 on 2024-02-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kamoku',
            fields=[
                ('kamokuid', models.IntegerField(primary_key=True, serialize=False)),
                ('kamoku_num', models.IntegerField()),
                ('kamoku_name', models.CharField(max_length=100)),
                ('kamoku_class', models.CharField(max_length=100)),
                ('kamoku_teacher', models.CharField(max_length=100)),
                ('kamoku_resume', models.CharField(max_length=100)),
                ('kamoku_day', models.CharField(max_length=100)),
                ('kamoku_time', models.IntegerField()),
                ('kamoku_department', models.CharField(max_length=100)),
                ('kamoku_unit', models.IntegerField()),
                ('kamoku_season', models.CharField(max_length=100))
            ],
        ),
    ]
