# Generated by Django 3.2.11 on 2024-02-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamoku',
            name='kamoku_season',
            field=models.CharField(max_length=100),
        ),
    ]
