# Generated by Django 3.2.11 on 2024-03-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0002_alter_kamoku_kamoku_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamoku',
            name='kamoku_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
