# Generated by Django 3.2.11 on 2024-03-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0003_kamoku_kamoku_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamoku',
            name='kamoku_class',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kamoku',
            name='kamoku_day',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kamoku',
            name='kamoku_department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kamoku',
            name='kamoku_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kamoku',
            name='kamoku_resume',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kamoku',
            name='kamoku_season',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kamoku',
            name='kamoku_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kamoku',
            name='kamoku_teacher',
            field=models.CharField(max_length=200),
        ),
    ]
